apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-health
spec:
  replicas: 2
  selector:
    matchLabels:
      name: simple-health
  template:
    metadata:
      labels: # labels to select/identify the deployment
        name: simple-health
    spec: # pod spec
      containers:
        - name: simple-health
          image: angelpeanuthub/simplehealth:production-{{.BUILD_NUMBER}}
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service

metadata:
  name: simple-health

spec:
  # type: LoadBalancer
  selector:
    name: simple-health
  ports:
    - name: http-port
      protocol: TCP
      port: 80
      targetPort: 8080

---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: trace-id
config:
  header_name: x-trace-id
plugin: correlation-id

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: health-ingress
  annotations:
    kubernetes.io/ingress.class: "kong"
    plugins.konghq.com: trace-id
spec:
  rules:
  - http:
      paths:
      - path: /simple
        backend:
          serviceName: simple-health
          servicePort: http-port